jobs:
  include:
    - language: nodejs
      nodejs: 14
      before_install:
        - cd frontend
      install:
        - npm install
      script:
        - npm run build

    - langauge: java
      jdk: openjdk8
      before_install:
        - cd backend
        - chmod +x mvnw
      script: "mvn cobertura:cobertura"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
