deploy:
  provider: script
  script: bash scripts/testScript.sh
    on:
    all_branches: true


jobs:
  # include:
  #   - language: nodejs
  #     nodejs: 14
  #     before_install:
  #       - cd frontend
  #     install:
  #       - npm install
  #     script:
  #       - npm run build

    - langauge: java
      jdk: openjdk11
      before_install:
        - cd backend
        - chmod +x mvnw
        - mkdir src/main/resources
        - echo ${COVERALLS_REPO_TOKEN}
      script:
        - mvn test
