jobs:
  include:
    - language: nodejs
      nodejs: 14
      before_install:
        - cd frontend
      install:
        - npm install
      script:
        - npm run build

    - langauge: java
      jdk: openjdk11
      before_install:
        - cd backend
        - chmod +x mvnw
      script:
        - mkdir src/main/resources
        - ls src/main
        - echo $NEO_USERNAME
        - mvn test
