jobs:
  include:
    - language: nodejs
      nodejs: 14
      before_install:
        - cd frontend
      install:
        - npm install
      script:
        - npm run build

    - langauge: java
      jdk: openjdk11
      before_install:
        - cd backend
        - chmod +x mvnw
      script:
        - mkdir src/main/resources
        - echo "spring.neo4j.uri=${NEO_URL}" > src/main/resources/application.properties
        - echo "spring.neo4j.authentication.username=${NEO_USERNAME}" >> src/main/resources/application.properties
        - echo "spring.neo4j.authentication.password=${NEO_PASS}" >> src/main/resources/application.properties
        - mvn test
