jobs:
  include:
    - language: nodejs
      nodejs: 14
      before_install:
        - cd frontend
      install:
        - npm install
      script:
        - npm run build

    - langauge: java
      jdk: openjdk11
      before_install:
        - cd backend
        - chmod +x mvnw
        - mkdir src/main/resources
      script:
        - echo hello
        - echo $COVERALLS_REPO_TOKEN
        - mvn test
