swagger: '2.0'
info:
  description: This is the API for the E-Park system
  version: 1.0.0
  title: E-Park Smart Water Monitor
host: 'localhost:8080'
basePath: /api
tags:
  - name: user
    description: User Subsystem
  - name: reporting
    description: Reporting Subsystem
  - name: analytics
    description: Analytics Subsystem
  - name: inspection
    description: Inspection Subsystem
  - name: devices
    description: Device Subsystem
  - name: notification
    description: Notification Subsystem
schemes:
  - https
  - http
paths:

definitions: