
#Workflow name
name: Unit and Integration Tests
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - master
      - development
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=COS301-SE-2021_E-Park-Smart-Water-Monitor

  #Test's job
  tests:
    name: Unit And Integration tests
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #Job's steps
    steps:
      - uses: actions/checkout@v1
      #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      #Set up Maven cache
      - name: Set up secrets
        run:
          cd /home/runner/work/E-Park-Smart-Water-Monitor/E-Park-Smart-Water-Monitor/backend/src/main/resources;
          touch application.properties;
          echo "${{secrets.A_PROPERTIES}}" > application.properties
      - name: Cache Maven packages
        #Allow caching dependencies.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Configure AWS Credentials
        run:
          ls -a;
          cd ~ ;
          echo "ls directories before";
          ls -a ;
          mkdir ~/.aws ;
          echo "ls directories after";
          ls -a ;
          cd ~/.aws;
          echo "aws before touch";
          ls -a;
          touch ~/.aws/credentials ;
          echo "aws after touch";
          ls -a;

          echo "[default]" >> ~/.aws/credentials;
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials;
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY}}" >>  ~/.aws/credentials ;
          echo "CAT-ing doc";
          cd /opt/hostedtoolcache/jdk/11.0.12/x64/conf/security;
          sed -i '1273s/.*/#jdk.security.caDistrustPolicies=SYMANTEC_TLS/' java.security;

      # Run Tests
      - name: Run Tests
        working-directory: ./backend
        run: mvn -B test
